src/Moonglade.Web/Controllers/AssetsController.cs
using MoongladePure.Caching.Filters;
using SixLabors.ImageSharp;

namespace MoongladePure.Web.Controllers;

[ApiController]
public class AssetsController : ControllerBase
{
    private readonly IMediator _mediator;
    private readonly IWebHostEnvironment _env;
    private readonly ILogger<AssetsController> _logger;

    public AssetsController(
        ILogger<AssetsController> logger,
        IMediator mediator,
        IWebHostEnvironment env)
    {
        _mediator = mediator;
        _env = env;
        _logger = logger;
    }

    [HttpGet("avatar")]
    [ResponseCache(Duration = 300)]
    public async Task<IActionResult> Avatar([FromServices] IBlogCache cache)
    {
        var fallbackImageFile = Path.Join($"{_env.WebRootPath}", "images", "default-avatar.png");

        try
        {
            var bytes = await cache.GetOrCreateAsync(CacheDivision.General, "avatar", async _ =>
            {
                _logger.LogTrace("Avatar not on cache, getting new avatar image...");

                var data = await _mediator.Send(new GetAssetQuery(AssetId.AvatarBase64));
                if (string.IsNullOrWhiteSpace(data)) return null;

                var avatarBytes = Convert.FromBase64String(data);
                return avatarBytes;
            });

            if (null == bytes)
            {
                return PhysicalFile(fallbackImageFile, "image/png");
            }

            return File(bytes, "image/png");
        }
        catch (FormatException e)
        {
            _logger.LogError(e, $"Error {nameof(Avatar)}(), Invalid Base64 string");
            return PhysicalFile(fallbackImageFile, "image/png");
        }
    }

    [Authorize]
    [HttpPost("avatar")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { CacheDivision.General, "avatar" })]
    public async Task<IActionResult> Avatar([FromBody] string base64Img)
    {
        base64Img = base64Img.Trim();
        if (!Helper.TryParseBase64(base64Img, out var base64Chars))
        {
            _logger.LogWarning("Bad base64 is used when setting avatar");
            return Conflict("Bad base64 data");
        }

        try
        {
            using var bmp = await Image.LoadAsync(new MemoryStream(base64Chars));
            if (bmp.Height != bmp.Width || bmp.Height + bmp.Width != 600)
            {
                return Conflict("Image size must be 300x300.");
            }
        }
        catch (Exception e)
        {
            _logger.LogError(e, "Invalid base64img Image");
            return Conflict(e.Message);
        }

        await _mediator.Publish(new SaveAssetCommand(AssetId.AvatarBase64, base64Img));

        return Ok();
    }

    #region Site Icon

    [ResponseCache(Duration = 3600)]
    [HttpHead(@"/{filename:regex(^(favicon|android-icon|apple-icon).*(ico|png)$)}")]
    [HttpGet(@"/{filename:regex(^(favicon|android-icon|apple-icon).*(ico|png)$)}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public IActionResult SiteIcon(string filename)
    {
        var iconBytes = MemoryStreamIconGenerator.GetIcon(filename);
        if (iconBytes is null) return NotFound();

        var contentType = "image/png";
        var ext = Path.GetExtension(filename);
        contentType = ext switch
        {
            ".png" => "image/png",
            ".ico" => "image/x-icon",
            _ => contentType
        };
        return File(iconBytes, contentType);
    }

    [Authorize]
    [HttpGet("siteicon")]
    public async Task<IActionResult> SiteIconOrigin()
    {
        var data = await _mediator.Send(new GetAssetQuery(AssetId.SiteIconBase64));
        var fallbackImageFile = Path.Join($"{_env.WebRootPath}", "images", "siteicon-default.png");
        if (string.IsNullOrWhiteSpace(data))
        {
            return PhysicalFile(fallbackImageFile, "image/png");
        }

        try
        {
            var siteIconBytes = Convert.FromBase64String(data);
            return File(siteIconBytes, "image/png");
        }
        catch (FormatException e)
        {
            _logger.LogError(e, $"Error {nameof(SiteIconOrigin)}(), Invalid Base64 string");
            return PhysicalFile(fallbackImageFile, "image/png");
        }
    }

    [Authorize]
    [HttpPost("siteicon")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> UpdateSiteIcon([FromBody] string base64Img)
    {
        base64Img = base64Img.Trim();
        if (!Helper.TryParseBase64(base64Img, out var base64Chars))
        {
            _logger.LogWarning("Bad base64 is used when setting site icon");
            return Conflict("Bad base64 data");
        }

        using var bmp = await Image.LoadAsync(new MemoryStream(base64Chars));
        if (bmp.Height != bmp.Width) return Conflict("image height must be equal to width");
        await _mediator.Publish(new SaveAssetCommand(AssetId.SiteIconBase64, base64Img));

        return NoContent();
    }

    #endregion
}

src/Moonglade.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace MoongladePure.Web.Controllers;

[Route("auth")]
public class AuthController : ControllerBase
{


    [HttpGet("signout")]
    [ProducesResponseType(StatusCodes.Status302Found)]
    public async Task<IActionResult> SignOut(int nounce = 1055)
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToPage("/Index");
    }

    [AllowAnonymous]
    [HttpGet("accessdenied")]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    public IActionResult AccessDenied() => Forbid();
}

src/Moonglade.Web/Pages/Shared/_Aside.cshtml
<aside class="col-lg-3">
    @if (BlogConfig.GeneralSettings.WidgetsProfile)
    {
        <section class="blog-info-desktop-lg text-light">
            <div class="card-with-avatar">
                <img class="card-bkimg" alt="" src="@BlogConfig.GeneralSettings.AvatarUrl" />
            </div>
            <div class="blog-info-photo-text text-center">
                <img src="@BlogConfig.GeneralSettings.AvatarUrl"
                 alt="@BlogConfig.GeneralSettings.OwnerName"
                 class="rounded-circle blogger-head-pic" />
                <div>
                    <h3 class="mt-3 text-white font-sairas">
                        @BlogConfig.GeneralSettings.OwnerName
                    </h3>
                    <p class="me-3 ms-3">
                        @BlogConfig.GeneralSettings.Description
                    </p>
                </div>
            </div>
        </section>
    }

    @if (!string.IsNullOrWhiteSpace(BlogConfig.GeneralSettings.SideBarCustomizedHtmlPitch))
    {
        @Html.Raw(BlogConfig.GeneralSettings.SideBarCustomizedHtmlPitch)
    }

    @if (BlogConfig.GeneralSettings.WidgetsTags)
    {
        <section id="aside-tags" class="mt-4 mb-4">
            <div class="card">
                <div class="card-header">@SharedLocalizer["Tags"]</div>
                <div class="card-body">
                    <cache expires-after="@TimeSpan.FromMinutes(60)">
                        @await Component.InvokeAsync("Tags")
                    </cache>
                    <hr />
                    <a asp-page="/Tags" class="card-link">
                        <i class="bi-tag me-1"></i>
                        @SharedLocalizer["All Tags"]
                    </a>
                </div>
            </div>
        </section>
    }

    @if (BlogConfig.GeneralSettings.WidgetsCategoryList)
    {
        <section id="aside-cats" class="mb-4">
            <div class="card">
                <div class="card-header">@SharedLocalizer["Categories"]</div>
                @await Component.InvokeAsync("CategoryList", new { isMenu = false })
            </div>
        </section>
    }

    @if (BlogConfig.GeneralSettings.WidgetsFriendLink)
    {
        <section id="aside-friendlink" class="mb-4">
            <cache expires-after="@TimeSpan.FromMinutes(60)">
                @await Component.InvokeAsync("FriendLink")
            </cache>
        </section>
    }

    @if (BlogConfig.GeneralSettings.WidgetsSubscriptionButtons)
    {
        <section id="aside-subscription" class="text-center mb-4">
            <a class="btn btn-sm btn-round btn-outline-secondary me-2" href="#" data-bs-toggle="modal" data-bs-target="#subscriptionmodal">
                <i class="bi-rss"></i>
                RSS / Atom
            </a>

            <a asp-controller="Subscription" asp-action="Opml" class="btn btn-sm btn-round btn-outline-secondary" target="_blank">
                <i class="bi-code-slash"></i>
                OPML
            </a>
        </section>
    }

    @if (BlogConfig.AdvancedSettings.ShowAdminLoginButton)
    {
        <div class="text-center">
            <a href="/admin" class="btn btn-sm btn-light">@SharedLocalizer["Admin Login"]</a>
        </div>
    }
</aside>

@if (BlogConfig.GeneralSettings.WidgetsSubscriptionButtons)
{
    <div class="modal fade" id="subscriptionmodal" tabindex="-1" role="dialog" aria-labelledby="subscriptionmodalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h6 class="modal-title" id="subscriptionmodalLabel">RSS / Atom Feed</h6>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-4">
                        <div class="col-6">
                            <a asp-controller="Subscription" asp-action="rss" class="btn w-100 btn-outline-success">
                                @SharedLocalizer["Latest Posts"] (RSS)
                            </a>
                        </div>
                        <div class="col-6">
                            <a asp-controller="Subscription" asp-action="Atom" class="btn w-100 btn-outline-success">
                                @SharedLocalizer["Latest Posts"] (Atom)
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        @await Component.InvokeAsync("RssList")
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@SharedLocalizer["Close"]</button>
                </div>
            </div>
        </div>
    </div>
}

src/Moonglade.Web/Pages/Shared/_EnvInfo.cshtml
@inject IWebHostEnvironment WebHostEnvironment

<environment exclude="Production">
    <div class="environment-info bg-danger text-light fixed-bottom text-center p-1 start-50 translate-middle-x d-print-none">
        You are accessing @WebHostEnvironment.EnvironmentName environment, data and changes may be isolated from production.
    </div>
</environment>

src/Moonglade.Web/Pages/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="57x57" href="~/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="~/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="~/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="~/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="~/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="~/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="~/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="~/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="~/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192" href="~/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="~/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
<link rel="manifest" href="~/manifest.webmanifest">
<meta name="msapplication-TileColor" content="#333333">
<meta name="msapplication-TileImage" content="~/ms-icon-144x144.png">
<meta name="theme-color" content="#333333">

src/Moonglade.Web/Pages/Shared/_Layout.cshtml
@using MoongladePure.Utils
@{
    if (string.IsNullOrEmpty(BlogConfig.GeneralSettings.AvatarUrl))
    {
        BlogConfig.GeneralSettings.AvatarUrl = Url.Action("Avatar", "Assets");
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    @if (IsSectionDefined("keywords"))
    {
        @await RenderSectionAsync("keywords", false)
    }
    else
    {
        <meta name="keywords" content="@Html.Raw(BlogConfig.GeneralSettings.MetaKeyword)" />
    }

    @await RenderSectionAsync("meta", false)
    @if (IsSectionDefined("opengraph"))
    {
        @await RenderSectionAsync("opengraph", false)
    }
    else
    {
        <partial name="_OpenGraph" />
    }

    @if (IsSectionDefined("metadescription"))
    {
        @await RenderSectionAsync("metadescription", false)
    }
    else
    {
        <metadesc description="@BlogConfig.GeneralSettings.Description" />
    }

    <title>
        @(ViewBag.TitlePrefix)@(null == ViewBag.TitlePrefix ? string.Empty : " - ")@BlogConfig.GeneralSettings.SiteTitle
    </title>

    @if (BlogConfig.ImageSettings.EnableCDNRedirect &&
    !string.IsNullOrWhiteSpace(BlogConfig.ImageSettings.CDNEndpoint))
    {
        <link rel="dns-prefetch" href="@Helper.GetDNSPrefetchUrl(BlogConfig.ImageSettings.CDNEndpoint)" />
    }


    <link rel="start" title="@BlogConfig.GeneralSettings.SiteTitle" href="~/" />
    <rss title="@BlogConfig.FeedSettings.RssTitle" href="@(Url.Action("Rss", "Subscription") ?? string.Empty)" />
    @if (BlogConfig.AdvancedSettings.EnableOpenSearch)
    {
        <opensearch href="/opensearch" title="@BlogConfig.GeneralSettings.SiteTitle" />
    }

    <link rel="manifest" href="/manifest.webmanifest" />
    <rsd href="/rsd" />
    <foaf href="/foaf.xml" />
    <partial name="_Favicons" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/base.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/rwd.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/darkmode.css" rel="stylesheet" asp-append-version="true" />
    @await RenderSectionAsync("head", false)
    <link href="~/theme.css" rel="stylesheet" asp-append-version="true" />
    @if (BlogConfig.CustomStyleSheetSettings.EnableCustomCss)
    {
        <link href="~/custom.css" rel="stylesheet" asp-append-version="true" />
    }
    <script src="~/js/3rd/jquery-3.6.3.min.js" asp-append-version="true"></script>
</head>
<body class="@ViewBag.BodyClass">
    @if (BlogConfig.ContentSettings.ShowCalloutSection)
    {
        <section class="call-out">
            @Html.Raw(BlogConfig.ContentSettings.CalloutSectionHtmlPitch)
        </section>
    }

    <header class="sticky-top d-print-none">
        <nav id="blog-nav" class="navbar navbar-expand-lg navbar-dark bg-accent1">
            <div class="container">
                <div class="animbrand">
                    <a class="moonglade-logo font-sairas navbar-brand animate" href="/">
                        @BlogConfig.GeneralSettings.LogoText
                    </a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#blog-navbar-content" aria-controls="blog-navbar-content" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="blog-navbar-content">
                    <ul class="navbar-nav me-auto">
                        <!-- System Nav Menu -->
                        <li id="navbar-dropdown-post" class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                                <i class="bi-folder2 nav-item-icon"></i>
                                <strong>@SharedLocalizer["Categories"]</strong>
                            </a>
                            @await Component.InvokeAsync("CategoryList", new { isMenu = true })
                        </li>

                        <li class="nav-item">
                            <a asp-page="/Tags" class="nav-link">
                                <i class="bi-tag nav-item-icon"></i>
                                <strong>@SharedLocalizer["Tags"]</strong>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-page="/Archive" class="nav-link">
                                <i class="bi-calendar3 nav-item-icon"></i>
                                <strong>@SharedLocalizer["Archive"]</strong>
                            </a>
                        </li>

                        @await Component.InvokeAsync("Menu")
                    </ul>
                    <form class="d-flex search-form my-2 my-lg-0" action="/search" method="get">
                        <input id="term"
                               class="form-control bg-transparent me-sm-2"
                               type="search"
                               value=""
                               title="@SharedLocalizer["Search"]"
                               aria-label="Search"
                               placeholder="@SharedLocalizer["Search"]"
                               name="term"
                               autofocus="autofocus"
                               maxlength="30">
                        <button class="btn btn-outline-light btn-search my-sm-0" type="submit" title="Search"><i class="bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <div id="page-content" class="content">
        @if (null != ViewBag.HideSideBar && ViewBag.HideSideBar)
        {
            @RenderBody()
        }
        else
        {
            <section class="profile-mobile d-block d-sm-none d-print-none">
                <div class="card-bkimg-container">
                    <img class="card-bkimg" alt="" src="@BlogConfig.GeneralSettings.AvatarUrl" />
                </div>
                <div class="blogger-intro-content">
                    <div class="row">
                        <div class="col-3">
                            <img src="@BlogConfig.GeneralSettings.AvatarUrl"
                             alt="@BlogConfig.GeneralSettings.OwnerName"
                             class="rounded-circle blogger-head-pic" />
                        </div>
                        <div class="col-9">
                            <h4 class="text-center">
                                @BlogConfig.GeneralSettings.ShortDescription
                            </h4>
                        </div>
                    </div>
                </div>
            </section>
            <div class="container mt-4 mb-5">
                <div class="row">
                    @if (BlogConfig.GeneralSettings.SideBarOption == SideBarOption.Left)
                    {
                        <partial name="_Aside" />
                    }

                    <section class="col-md-12 @(BlogConfig.GeneralSettings.SideBarOption == SideBarOption.Disabled ? null : "col-lg-9")">
                        @RenderBody()
                    </section>

                    @if (BlogConfig.GeneralSettings.SideBarOption == SideBarOption.Right)
                    {
                        <partial name="_Aside" />
                    }
                </div>
            </div>
        }
    </div>
    <div class="clearfix"></div>
    <partial name="_Footer" />
    <partial name="_EnvInfo" />
    <partial name="_Toast" />

    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-utc-time/time.js" asp-append-version="true"></script>
    <script type="module" src="~/js/app/base.js" asp-append-version="true"></script>
    <script src="~/js/app/httpService.js" asp-append-version="true"></script>
    <script>
        new UtcTime({
        });
    </script>

    @if (BlogConfig.GeneralSettings.AutoDarkLightTheme && (ViewBag.DisableLightSwitch == null || !ViewBag.DisableLightSwitch))
    {
        <script type="module">
            import * as theme from '/js/app/theme.module.js'
            window.theme = theme;

            if (window.matchMedia && window.theme) {
                if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
                    theme.useDarkMode();
                } else {
                    theme.useLightMode();
                }
            }
        </script>
    }

    @await RenderSectionAsync("scripts", false)
</body>
</html>

src/Moonglade.Web/Pages/Shared/_LayoutAdmin.cshtml
@{
    var currentPage = ViewContext.RouteData.Values["Page"]?.ToString();

    if (string.IsNullOrEmpty(BlogConfig.GeneralSettings.AvatarUrl))
    {
        BlogConfig.GeneralSettings.AvatarUrl = Url.Action("Avatar", "Assets");
    }
}
<!DOCTYPE html>
<html>

<head>
    <title>
        @BlogConfig.GeneralSettings.SiteTitle @SharedLocalizer["Admin"] @(ViewBag.Title != null ? $"- {ViewBag.Title}" : null)
    </title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <meta name="keywords" content="@Html.Raw(BlogConfig.GeneralSettings.MetaKeyword)" />
    <link rel="start" title="@BlogConfig.GeneralSettings.SiteTitle" href="~/" />
    <rss title="@BlogConfig.FeedSettings.RssTitle" href="@(Url.Action("Rss", "Subscription") ?? string.Empty)" />
    @if (BlogConfig.AdvancedSettings.EnableOpenSearch)
    {
        <opensearch href="/opensearch" title="@BlogConfig.GeneralSettings.SiteTitle" />
    }
    <foaf href="/foaf.xml" />
    <partial name="_Favicons" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="~/css/base.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/rwd.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/admin.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/theme.css" rel="stylesheet" asp-append-version="true" />
    @await RenderSectionAsync("head", false)
    <script src="~/js/3rd/jquery-3.6.3.min.js" asp-append-version="true"></script>
</head>

<body class="admin-body bg-gray-1">
    <nav class="admin-navbar navbar sticky-top navbar-expand-lg navbar-dark bg-accent2">
        <a class="navbar-brand font-sairas" asp-page="/Admin/Post">
            @BlogConfig.GeneralSettings.SiteTitle
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">

                <li class="nav-item">
                    <a class="nav-link" asp-page="/Settings/General">
                        <i class="bi-gear"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-page="/Admin/About">
                        <i class="bi-info-circle"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-page="/Index" target="_blank">
                        <i class="bi-house"></i>
                    </a>
                </li>
            </ul>

            <span class="navbar-text me-2">
                <img src="@BlogConfig.GeneralSettings.AvatarUrl" alt="@BlogConfig.GeneralSettings.OwnerName"
                     class="rounded-circle admin-nav-head-pic me-1" />
                <userinfo user="User"></userinfo>
            </span>

            <a class="navbar-text d-inline-block" asp-controller="Auth" asp-action="SignOut" title="Sign Out">
                <i class="bi-box-arrow-right"></i>
            </a>
        </div>
    </nav>
    <div class="d-flex admin-body-wrapper">
        <aside class="admin-nav">
            <section class="admin-nav-section rounded-3 shadow-sm border bg-white mt-4 mb-3">
                <div class="list-group list-group-flush">
                    <a asp-page="/Admin/Post"
                       class="list-group-item list-group-item-action @(currentPage is "/Admin/Post" or "/Admin/EditPost" or "/Admin/Draft" or "/Admin/PostInsights" or "/Admin/RecycleBin" ? "active" : null)">
                        <i class="bi-file-earmark-richtext admin-nav-icon"></i>
                        @SharedLocalizer["Posts"]
                    </a>
                    <a asp-page="/Admin/BlogPage"
                       class="list-group-item list-group-item-action @(currentPage is "/Admin/BlogPage" or "/Admin/EditPage" ? "active" : null)">
                        <i class="bi-file-earmark-post admin-nav-icon"></i>
                        @SharedLocalizer["Pages"]
                    </a>
                    <a asp-page="/Admin/Category"
                       class="list-group-item list-group-item-action @(currentPage is "/Admin/Category" ? "active" : null)">
                        <i class="bi-folder2 admin-nav-icon"></i>
                        @SharedLocalizer["Categories"]
                    </a>
                    @if (BlogConfig.ContentSettings.CommentProvider == CommentProvider.BuiltIn)
                    {
                        <a asp-page="/Admin/Comments"
                       class="list-group-item list-group-item-action @(currentPage is "/Admin/Comments" ? "active" : null)">
                            <i class="bi-chat-left-text admin-nav-icon"></i>
                            @SharedLocalizer["Comments"]
                        </a>
                    }
                    <a asp-page="/Admin/Tags"
                       class="list-group-item list-group-item-action @(currentPage is "/Admin/Tags" ? "active" : null)">
                        <i class="bi-tag admin-nav-icon"></i>
                        @SharedLocalizer["Tags"]
                    </a>
                    <a asp-page="/Admin/Menu"
                       class="list-group-item list-group-item-action @(currentPage is "/Admin/Menu" ? "active" : null)">
                        <i class="bi-menu-button-wide admin-nav-icon"></i>
                        @SharedLocalizer["Menus"]
                    </a>
                    <a asp-page="/Admin/FriendLink"
                       class="list-group-item list-group-item-action @(currentPage is "/Admin/FriendLink" ? "active" : null)">
                        <i class="bi-link-45deg admin-nav-icon"></i>
                        @SharedLocalizer["Friend Links"]
                    </a>
                    <a asp-page="/Admin/LocalAccount"
                       class="list-group-item list-group-item-action @(currentPage is "/Admin/LocalAccount" ? "active" : null)">
                            <i class="bi-people admin-nav-icon"></i>
                            @SharedLocalizer["Accounts"]
                    </a>
                </div>
            </section>
        </aside>
        <div class="admin-main rounded-3 shadow-sm border bg-white mt-4 mb-4 me-3 ms-3">
            @RenderBody()
        </div>
    </div>

    <partial name="_Toast" />

    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script type="module" src="~/js/app/base.js" asp-append-version="true"></script>
    <script src="~/js/app/httpService.js"></script>
    <script src="~/js/3rd/jquery.are-you-sure.min.js"></script>
    <script src="~/lib/jquery-utc-time/time.js" asp-append-version="true"></script>
    <script>
        new UtcTime({
        });
    </script>
    @await RenderSectionAsync("scripts", false)
</body>

</html>