src/Moonglade.Web/Controllers/ImageController.cs
using Edi.ImageWatermark;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using SixLabors.ImageSharp;

namespace MoongladePure.Web.Controllers;

[ApiController]
[Route("image")]
public class ImageController : ControllerBase
{
    private readonly IBlogImageStorage _imageStorage;
    private readonly ILogger<ImageController> _logger;
    private readonly IBlogConfig _blogConfig;
    private readonly IMemoryCache _cache;
    private readonly IFileNameGenerator _fileNameGen;
    private readonly IConfiguration _configuration;
    private readonly ImageStorageSettings _imageStorageSettings;

    public ImageController(
        IBlogImageStorage imageStorage,
        ILogger<ImageController> logger,
        IBlogConfig blogConfig,
        IMemoryCache cache,
        IFileNameGenerator fileNameGen,
        IConfiguration configuration,
        IOptions<ImageStorageSettings> imageStorageSettings)
    {
        _imageStorage = imageStorage;
        _logger = logger;
        _blogConfig = blogConfig;
        _cache = cache;
        _fileNameGen = fileNameGen;
        _configuration = configuration;
        _imageStorageSettings = imageStorageSettings.Value;
    }

    [HttpGet(@"{filename:regex((?!-)([[a-z0-9-]]+)\.(png|jpg|jpeg|gif|bmp))}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status302Found)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Image(string filename)
    {
        var invalidChars = Path.GetInvalidFileNameChars();
        if (filename.IndexOfAny(invalidChars) >= 0)
        {
            return BadRequest("invalid filename");
        }

        // Fallback method for legacy "/image/..." references (e.g. from third party websites)
        if (_blogConfig.ImageSettings.EnableCDNRedirect)
        {
            var imageUrl = _blogConfig.ImageSettings.CDNEndpoint.CombineUrl(filename);
            return Redirect(imageUrl);
        }

        var image = await _cache.GetOrCreateAsync(filename, async entry =>
        {
            entry.SlidingExpiration = TimeSpan.FromMinutes(int.Parse(_configuration["CacheSlidingExpirationMinutes:Image"] ?? "0"));
            var imageInfo = await _imageStorage.GetAsync(filename);
            return imageInfo;
        });

        if (null == image) return NotFound();

        return File(image.ImageBytes, image.ImageContentType);
    }

    [Authorize]
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> Image(IFormFile file, [FromQuery] bool skipWatermark = false)
    {
        if (file is null or { Length: <= 0 })
        {
            _logger.LogError("file is null");
            return BadRequest();
        }

        var name = Path.GetFileName(file.FileName);

        var ext = Path.GetExtension(name).ToLower();
        var allowedExts = _imageStorageSettings.AllowedExtensions;

        if (null == allowedExts || !allowedExts.Any())
        {
            throw new InvalidDataException($"{nameof(ImageStorageSettings.AllowedExtensions)} is empty.");
        }

        if (!allowedExts.Contains(ext))
        {
            _logger.LogError("Invalid file extension: {Ext}", ext);
            return BadRequest();
        }

        var primaryFileName = _fileNameGen.GetFileName(name);
        var secondaryFieName = _fileNameGen.GetFileName(name, "origin");

        await using var stream = new MemoryStream();
        await file.CopyToAsync(stream);

        stream.Position = 0;

        // Add watermark
        MemoryStream watermarkedStream = null;
        if (_blogConfig.ImageSettings.IsWatermarkEnabled && !skipWatermark)
        {
            if (string.Compare(".gif", ext, StringComparison.OrdinalIgnoreCase) != 0)
            {
                using var watermarker = new ImageWatermarker(stream, ext, _blogConfig.ImageSettings.WatermarkSkipPixel);

                watermarkedStream = watermarker.AddWatermark(
                    _blogConfig.ImageSettings.WatermarkText,
                    Color.FromRgba(
                        (byte)_blogConfig.ImageSettings.WatermarkColorR,
                        (byte)_blogConfig.ImageSettings.WatermarkColorG,
                        (byte)_blogConfig.ImageSettings.WatermarkColorB,
                        (byte)_blogConfig.ImageSettings.WatermarkColorA),
                    WatermarkPosition.BottomRight,
                    15,
                    _blogConfig.ImageSettings.WatermarkFontSize);
            }
            else
            {
                _logger.LogInformation("Skipped watermark for extension name: {Ext}", ext);
            }
        }

        var finalName = await _imageStorage.InsertAsync(primaryFileName,
            watermarkedStream is not null ?
                watermarkedStream.ToArray() :
                stream.ToArray());

        if (_blogConfig.ImageSettings.IsWatermarkEnabled && _blogConfig.ImageSettings.KeepOriginImage || !skipWatermark)
        {
            var arr = stream.ToArray();
            _ = Task.Run(async () => await _imageStorage.InsertAsync(secondaryFieName, arr));
        }

        _logger.LogInformation("Image {PrimaryFileName} uploaded", primaryFileName);
        var location = $"/image/{finalName}";
        var filename = location;

        return Ok(new
        {
            location,
            filename
        });
    }
}

src/Moonglade.Web/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Localization;
using MoongladePure.Caching.Filters;
using NUglify;

namespace MoongladePure.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class SettingsController : ControllerBase
{
    #region Private Fields

    private readonly IMediator _mediator;
    private readonly IBlogConfig _blogConfig;
    private readonly ILogger<SettingsController> _logger;

    #endregion

    public SettingsController(
        IBlogConfig blogConfig,
        ILogger<SettingsController> logger,
        IMediator mediator)
    {
        _blogConfig = blogConfig;
        _logger = logger;
        _mediator = mediator;
    }

    [AllowAnonymous]
    [HttpGet("set-lang")]
    public IActionResult SetLanguage(string culture, string returnUrl)
    {
        try
        {
            if (string.IsNullOrWhiteSpace(culture)) return BadRequest();

            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new(culture)),
                new() { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(string.IsNullOrWhiteSpace(returnUrl) ? "~/" : returnUrl);
        }
        catch (Exception e)
        {
            _logger.LogError(e, "Crashed when setting language for {Culture} with {ReturnUrl}", culture, returnUrl);

            // We shall not respect the return URL now, because the returnUrl might be hacking.
            return LocalRedirect("~/");
        }
    }

    [HttpPost("general")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { CacheDivision.General, "theme" })]
    public async Task<IActionResult> General(GeneralSettings model)
    {
        model.AvatarUrl = _blogConfig.GeneralSettings.AvatarUrl;

        _blogConfig.GeneralSettings = model;

        await SaveConfigAsync(_blogConfig.GeneralSettings);

        AppDomain.CurrentDomain.SetData("CurrentThemeColor", null);

        return NoContent();
    }

    [HttpPost("content")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Content(ContentSettings model)
    {
        _blogConfig.ContentSettings = model;

        await SaveConfigAsync(_blogConfig.ContentSettings);
        return NoContent();
    }

    [HttpPost("subscription")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Subscription(FeedSettings model)
    {
        _blogConfig.FeedSettings = model;

        await SaveConfigAsync(_blogConfig.FeedSettings);
        return NoContent();
    }

    [HttpPost("watermark")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> Image(ImageSettings model, [FromServices] IBlogImageStorage imageStorage)
    {
        _blogConfig.ImageSettings = model;

        if (model.EnableCDNRedirect)
        {
            if (null != _blogConfig.GeneralSettings.AvatarUrl
            && !_blogConfig.GeneralSettings.AvatarUrl.StartsWith(model.CDNEndpoint))
            {
                try
                {
                    var avatarData = await _mediator.Send(new GetAssetQuery(AssetId.AvatarBase64));

                    if (!string.IsNullOrWhiteSpace(avatarData))
                    {
                        var avatarBytes = Convert.FromBase64String(avatarData);
                        var fileName = $"avatar-{AssetId.AvatarBase64:N}.png";
                        fileName = await imageStorage.InsertAsync(fileName, avatarBytes);
                        _blogConfig.GeneralSettings.AvatarUrl = _blogConfig.ImageSettings.CDNEndpoint.CombineUrl(fileName);

                        await SaveConfigAsync(_blogConfig.GeneralSettings);
                    }
                }
                catch (FormatException e)
                {
                    _logger.LogError(e, $"Error {nameof(Image)}(), Invalid Base64 string");
                }
            }
        }
        else
        {
            _blogConfig.GeneralSettings.AvatarUrl = Url.Action("Avatar", "Assets");
            await SaveConfigAsync(_blogConfig.GeneralSettings);
        }

        await SaveConfigAsync(_blogConfig.ImageSettings);

        return NoContent();
    }

    [HttpPost("advanced")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Advanced(AdvancedSettings model)
    {
        model.MetaWeblogPasswordHash = !string.IsNullOrWhiteSpace(model.MetaWeblogPassword) ?
            Helper.HashPassword(model.MetaWeblogPassword) :
            _blogConfig.AdvancedSettings.MetaWeblogPasswordHash;

        _blogConfig.AdvancedSettings = model;

        await SaveConfigAsync(_blogConfig.AdvancedSettings);
        return NoContent();
    }

    [HttpPost("shutdown")]
    [ProducesResponseType(StatusCodes.Status202Accepted)]
    public IActionResult Shutdown([FromServices] IHostApplicationLifetime applicationLifetime)
    {
        _logger.LogWarning("Shutdown is requested by \'{IdentityName}\'", User.Identity?.Name);
        applicationLifetime.StopApplication();
        return Accepted();
    }

    [HttpPost("reset")]
    [ProducesResponseType(StatusCodes.Status202Accepted)]
    public async Task<IActionResult> Reset([FromServices] BlogDbContext context,
        [FromServices] IHostApplicationLifetime applicationLifetime)
    {
        _logger.LogWarning("System reset is requested by \'{IdentityName}\', IP: {ClientIp}", User.Identity?.Name, Helper.GetClientIP(HttpContext));

        await context.ClearAllDataAsync();

        applicationLifetime.StopApplication();
        return Accepted();
    }

    [HttpPost("custom-css")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> CustomStyleSheet(CustomStyleSheetSettings model)
    {
        if (model.EnableCustomCss && string.IsNullOrWhiteSpace(model.CssCode))
        {
            ModelState.AddModelError(nameof(CustomStyleSheetSettings.CssCode), "CSS Code is required");
            return BadRequest(ModelState.CombineErrorMessages());
        }

        var uglifyTest = Uglify.Css(model.CssCode);
        if (uglifyTest.HasErrors)
        {
            foreach (var err in uglifyTest.Errors)
            {
                ModelState.AddModelError(model.CssCode, err?.ToString() ?? string.Empty );
            }
            return BadRequest(ModelState.CombineErrorMessages());
        }

        _blogConfig.CustomStyleSheetSettings = model;

        await SaveConfigAsync(_blogConfig.CustomStyleSheetSettings);
        return NoContent();
    }

    [HttpGet("password/generate")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public IActionResult GeneratePassword()
    {
        var password = Helper.GeneratePassword(10, 3);
        return Ok(new
        {
            ServerTimeUtc = DateTime.UtcNow,
            Password = password
        });
    }

    private async Task SaveConfigAsync<T>(T blogSettings) where T : IBlogSettings
    {
        var kvp = _blogConfig.UpdateAsync(blogSettings);
        await _mediator.Send(new UpdateConfigurationCommand(kvp.Key, kvp.Value));
    }
}

src/Moonglade.Web/Controllers/SubscriptionController.cs
using MoongladePure.Core.CategoryFeature;
using MoongladePure.Syndication;
using System.ComponentModel.DataAnnotations;

namespace MoongladePure.Web.Controllers;

[ApiController]
public class SubscriptionController : ControllerBase
{
    private readonly IBlogConfig _blogConfig;
    private readonly IBlogCache _cache;
    private readonly IMediator _mediator;

    public SubscriptionController(
        IBlogConfig blogConfig,
        IBlogCache cache,
        IMediator mediator)
    {
        _blogConfig = blogConfig;
        _cache = cache;
        _mediator = mediator;
    }

    [HttpGet("opml")]
    public async Task<IActionResult> Opml()
    {
        var cats = await _mediator.Send(new GetCategoriesQuery());
        var catInfos = cats.Select(c => new KeyValuePair<string, string>(c.DisplayName, c.RouteName));
        var rootUrl = Helper.ResolveRootUrl(HttpContext);

        var oi = new OpmlDoc
        {
            SiteTitle = $"{_blogConfig.GeneralSettings.SiteTitle} - OPML",
            ContentInfo = catInfos,
            HtmlUrl = $"{rootUrl}/post",
            XmlUrl = $"{rootUrl}/rss",
            XmlUrlTemplate = $"{rootUrl}/rss/[catTitle]",
            HtmlUrlTemplate = $"{rootUrl}/category/[catTitle]"
        };

        var xml = await _mediator.Send(new GetOpmlQuery(oi));
        return Content(xml, "text/xml");
    }

    [HttpGet("rss/{routeName?}")]
    public async Task<IActionResult> Rss([MaxLength(64)] string routeName = null)
    {
        bool hasRoute = !string.IsNullOrWhiteSpace(routeName);
        var route = hasRoute ? routeName.ToLower().Trim() : null;

        return await _cache.GetOrCreateAsync(
            hasRoute ? CacheDivision.RssCategory : CacheDivision.General, route ?? "rss", async entry =>
            {
                entry.SlidingExpiration = TimeSpan.FromHours(1);

                var xml = await _mediator.Send(new GetRssStringQuery(routeName));
                if (string.IsNullOrWhiteSpace(xml))
                {
                    return (IActionResult)NotFound();
                }

                return Content(xml, "text/xml");
            });
    }

    [HttpGet("atom")]
    public async Task<IActionResult> Atom()
    {
        return await _cache.GetOrCreateAsync(CacheDivision.General, "atom", async entry =>
        {
            entry.SlidingExpiration = TimeSpan.FromHours(1);

            var xml = await _mediator.Send(new GetAtomStringQuery());
            return Content(xml, "text/xml");
        });
    }
}

src/Moonglade.Web/Pages/Settings/Advanced.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MoongladePure.Web.Pages.Settings;

public class AdvancedModel : PageModel
{
    private readonly IBlogConfig _blogConfig;

    public AdvancedSettings ViewModel { get; set; }

    public AdvancedModel(IBlogConfig blogConfig) => _blogConfig = blogConfig;

    public void OnGet() => ViewModel = _blogConfig.AdvancedSettings;
}

src/Moonglade.Web/Pages/Settings/Content.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MoongladePure.Web.Pages.Settings;

public class ContentModel : PageModel
{
    private readonly IBlogConfig _blogConfig;
    public ContentSettings ViewModel { get; set; }

    public ContentModel(IBlogConfig blogConfig) => _blogConfig = blogConfig;

    public void OnGet() => ViewModel = _blogConfig.ContentSettings;
}

src/Moonglade.Web/Pages/Settings/CustomStyleSheet.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MoongladePure.Web.Pages.Settings;

public class CustomStyleSheetModel : PageModel
{
    private readonly IBlogConfig _blogConfig;

    public CustomStyleSheetSettings ViewModel { get; set; }

    public CustomStyleSheetModel(IBlogConfig blogConfig) => _blogConfig = blogConfig;

    public void OnGet() => ViewModel = _blogConfig.CustomStyleSheetSettings;
}

src/Moonglade.Web/Pages/Settings/General.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MoongladePure.Web.Pages.Settings;

public class GeneralModel : PageModel
{
    private readonly IBlogConfig _blogConfig;
    private readonly IMediator _mediator;

    public GeneralSettings ViewModel { get; set; }

    public CreateThemeRequest ThemeRequest { get; set; }

    public IReadOnlyList<ThemeSegment> Themes { get; set; }

    public GeneralModel(IBlogConfig blogConfig, IMediator mediator)
    {
        _blogConfig = blogConfig;
        _mediator = mediator;
    }

    public async Task OnGetAsync()
    {
        ViewModel = _blogConfig.GeneralSettings;

        Themes = await _mediator.Send(new GetAllThemeSegmentQuery());
    }
}

src/Moonglade.Web/Pages/Settings/CustomStyleSheet.cshtml
@page "/admin/settings/custom-css"
@model MoongladePure.Web.Pages.Settings.CustomStyleSheetModel


@{
    <script>
        var needLoadInitValues = @((!string.IsNullOrWhiteSpace(Model.ViewModel.CssCode)).ToString().ToLower());
    </script>
}

@section scripts{
    <script type="text/javascript" src="https://unpkg.com/monaco-editor@latest/min/vs/loader.js"></script>
    <script>
        require.config({ paths: { 'vs': 'https://unpkg.com/monaco-editor@latest/min/vs' }});
        // Before loading vs/editor/editor.main, define a global MonacoEnvironment that overwrites
        // the default worker url location (used when creating WebWorkers). The problem here is that
        // HTML5 does not allow cross-domain web workers, so we need to proxy the instantiation of
        // a web worker through a same-domain script
        window.MonacoEnvironment = {
            getWorkerUrl: function(workerId, label) {
                return `data:text/javascript;charset=utf-8,${encodeURIComponent(`
        self.MonacoEnvironment = {
          baseUrl: 'https://unpkg.com/monaco-editor@latest/min/'
        };
        importScripts('https://unpkg.com/monaco-editor@latest/min/vs/base/worker/workerMain.js');`
                )}`;
            }
        };

        var cssContentEditor = null;

        require(['vs/editor/editor.main'], function () {
            initCssEditor();
        });

        var initCssEditor = function () {
            var cssContentEditorDiv = document.getElementById('CssContentEditor');
            cssContentEditor = monaco.editor.create(cssContentEditorDiv, {
                language: 'css'
            });
            cssContentEditor.layout();

            if (needLoadInitValues) {
                var cssValue = document.querySelector("#ViewModel_CssCode").value;
                window.cssContentEditor.setValue(cssValue);
            }
        }

        var assignEditorValues = function () {
            var cssValue = window.cssContentEditor.getValue();
            document.querySelector("#ViewModel_CssCode").value = cssValue;
        }
    </script>
    <script type="module">
        import * as settings from '/js/app/admin.settings.module.js';
        
        function handleSubmit(event) {
            assignEditorValues();
            settings.handleSettingsSubmit(event);
        }

        const form = document.querySelector('#form-settings');
        form.addEventListener('submit', handleSubmit);
    </script>
}

@section head{
    <style>
        .monaco-target {
            border: 1px solid #dee2e6;
            width: 100%;
            min-height: 512px;
        }
    </style>
}

<partial name="_SettingsHeader" />
<div class="ps-4 pe-4">
    <form id="form-settings" asp-controller="Settings" asp-action="CustomStyleSheet">
        <div class="form-check form-switch mb-3">
            <input type="hidden" name="EnableCustomCss" value="false">
            <input type="checkbox" name="EnableCustomCss" value="true" class="form-check-input" @(Model.ViewModel.EnableCustomCss ? "checked" : null)>
            <label asp-for="ViewModel.EnableCustomCss" class="form-check-label"></label>
        </div>

        <div id="CssContentEditor" class="monaco-target">

        </div>
        <textarea asp-for="ViewModel.CssCode" class="settings-csscontent-textarea d-none"></textarea>

        <div class="mt-3">
            <button type="submit" class="btn btn-outline-accent" id="btn-save-settings">
                @SharedLocalizer["Save"]
            </button>
        </div>
    </form>
</div>

src/Moonglade.Web/Pages/Settings/Subscription.cshtml
@page "/admin/settings/subscription"
@model MoongladePure.Web.Pages.Settings.SubscriptionModel
@section scripts{
    <script type="module">
        import * as settings from '/js/app/admin.settings.module.js';
        
        const form = document.querySelector('#form-settings');
        form.addEventListener('submit', settings.handleSettingsSubmit);
    </script>
}

<partial name="_SettingsHeader" />
<div class="ps-4 pe-4 pt-4">
    <form id="form-settings" asp-controller="Settings" asp-action="Subscription" spellcheck="false">
        <div class="row">
            <div class="col-lg-6">
                <div class="row g-3 align-items-center settings-entry mb-4">
                    <div class="col-auto">
                        <i class="bi-hr settings-entry-icon"></i>
                    </div>
                    <div class="col">
                        <label asp-for="ViewModel.RssTitle"></label>
                        <div class="form-text">
                            Title on RSS/ATOM readers
                        </div>
                    </div>
                    <div class="col-md-5">
                        <input asp-for="ViewModel.RssTitle" class="form-control" required maxlength="64"/>
                    </div>
                </div>

                <div class="row g-3 align-items-center settings-entry mb-4">
                    <div class="col-auto">
                        <i class="bi-list-ol settings-entry-icon"></i>
                    </div>
                    <div class="col">
                        <label asp-for="ViewModel.RssItemCount"></label>
                        <div class="form-text">@SharedLocalizer["The number of entries to include in RSS feed."]</div>
                    </div>
                    <div class="col-md-5">
                        <input asp-for="ViewModel.RssItemCount" class="form-control" required />
                    </div>
                </div>

                <div class="row g-3 align-items-center settings-entry mb-4">
                    <div class="col-auto">
                        <i class="bi-justify-left settings-entry-icon"></i>
                    </div>
                    <div class="col">
                        <label asp-for="ViewModel.UseFullContent" class="form-check-label"></label>
                    </div>
                    <div class="col-md-5 text-end">
                        <div class="form-check form-switch">
                            <input type="hidden" name="UseFullContent" value="false">
                            <input type="checkbox" name="UseFullContent" value="true" class="form-check-input" @(Model.ViewModel.UseFullContent ? "checked" : null)/>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="mb-2">
            <input id="btn-save-settings" type="submit" value="@SharedLocalizer["Save"]" class="btn btn-outline-accent" />
        </div>
    </form>
</div>

src/Moonglade.Web/Pages/Settings/_SettingsHeader.cshtml
@{
    var currentPage = ViewContext.RouteData.Values["Page"]?.ToString();
}

<div class="admin-toolbar ps-4 pe-4 pt-2 pb-2 border-bottom mb-3 shadow-sm d-flex">
    <ul class="nav nav-pills">
        <li role="presentation" class="nav-item nav-item-non-margin">
            <a class="nav-link @(currentPage == "/Settings/General" ? "active" : null)" asp-page="./General">@SharedLocalizer["General"]</a>
        </li>
        <li role="presentation" class="nav-item nav-item-non-margin">
            <a class="nav-link @(currentPage == "/Settings/Content" ? "active" : null)" asp-page="./Content">@SharedLocalizer["Content"]</a>
        </li>
        <li role="presentation" class="nav-item nav-item-non-margin">
            <a class="nav-link @(currentPage == "/Settings/Image" ? "active" : null)" asp-page="./Image">@SharedLocalizer["Image"]</a>
        </li>
        <li role="presentation" class="nav-item nav-item-non-margin">
            <a class="nav-link @(currentPage == "/Settings/Subscription" ? "active" : null)" asp-page="./Subscription">@SharedLocalizer["Subscription"]</a>
        </li>
        <li role="presentation" class="nav-item nav-item-non-margin">
            <a class="nav-link @(currentPage == "/Settings/CustomStyleSheet" ? "active" : null)" asp-page="./CustomStyleSheet">@SharedLocalizer["Custom CSS"]</a>
        </li>
        <li role="presentation" class="nav-item nav-item-non-margin">
            <a class="nav-link @(currentPage == "/Settings/Advanced" ? "active" : null)" asp-page="./Advanced">@SharedLocalizer["Advanced"]</a>
        </li>
    </ul>
</div>