src/Moonglade.Web/Controllers/PostController.cs
using MoongladePure.Caching.Filters;
using MoongladePure.Core.PostFeature;
using MoongladePure.Web.Attributes;
using NUglify;
using System.ComponentModel.DataAnnotations;

namespace MoongladePure.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class PostController : ControllerBase
{
    private readonly IMediator _mediator;

    private readonly ILogger<PostController> _logger;

    public PostController(
        IMediator mediator,
        ILogger<PostController> logger)
    {
        _mediator = mediator;
        _logger = logger;
    }

    [HttpPost("createoredit")]
    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[]
    {
        BlogCacheType.SiteMap |
        BlogCacheType.Subscription |
        BlogCacheType.PagingCount
    })]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> CreateOrEdit(PostEditModel model, [FromServices] LinkGenerator linkGenerator)
    {
        try
        {
            if (!ModelState.IsValid) return Conflict(ModelState.CombineErrorMessages());

            if (!string.IsNullOrWhiteSpace(model.InlineCss))
            {
                var uglifyTest = Uglify.Css(model.InlineCss);
                if (uglifyTest.HasErrors)
                {
                    foreach (var err in uglifyTest.Errors)
                    {
                        ModelState.AddModelError(model.InlineCss, err?.ToString() ?? string.Empty);
                    }
                    return BadRequest(ModelState.CombineErrorMessages());
                }

                model.InlineCss = uglifyTest.Code;
            }

            if (model.ChangePublishDate &&
                model.PublishDate.HasValue &&
                model.PublishDate.GetValueOrDefault().Year >= 1975)
            {
                model.PublishDate =model.PublishDate.Value;
            }

            var postEntity = model.PostId == Guid.Empty ?
                await _mediator.Send(new CreatePostCommand(model)) :
                await _mediator.Send(new UpdatePostCommand(model.PostId, model));

            return Ok(new { PostId = postEntity.Id });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error Creating New Post");
            return Conflict(ex.Message);
        }
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[]
    {
        BlogCacheType.SiteMap |
        BlogCacheType.Subscription |
        BlogCacheType.PagingCount
    })]
    [HttpPost("{postId:guid}/restore")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Restore([NotEmpty] Guid postId)
    {
        await _mediator.Send(new RestorePostCommand(postId));
        return NoContent();
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[]
    {
        BlogCacheType.SiteMap |
        BlogCacheType.Subscription |
        BlogCacheType.PagingCount
    })]
    [HttpDelete("{postId:guid}/recycle")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Delete([NotEmpty] Guid postId)
    {
        await _mediator.Send(new DeletePostCommand(postId, true));
        return NoContent();
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { BlogCacheType.Subscription | BlogCacheType.SiteMap })]
    [HttpDelete("{postId:guid}/destroy")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> DeleteFromRecycleBin([NotEmpty] Guid postId)
    {
        await _mediator.Send(new DeletePostCommand(postId));
        return NoContent();
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { BlogCacheType.Subscription | BlogCacheType.SiteMap })]
    [HttpDelete("recyclebin")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> EmptyRecycleBin()
    {
        await _mediator.Send(new PurgeRecycledCommand());
        return NoContent();
    }

    [HttpPost("keep-alive")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public IActionResult KeepAlive([MaxLength(16)] string nonce)
    {
        return Ok(new
        {
            ServerTime = DateTime.UtcNow,
            Nonce = nonce
        });
    }
}

src/Moonglade.Web/Controllers/SubscriptionController.cs
using MoongladePure.Core.CategoryFeature;
using MoongladePure.Syndication;
using System.ComponentModel.DataAnnotations;

namespace MoongladePure.Web.Controllers;

[ApiController]
public class SubscriptionController : ControllerBase
{
    private readonly IBlogConfig _blogConfig;
    private readonly IBlogCache _cache;
    private readonly IMediator _mediator;

    public SubscriptionController(
        IBlogConfig blogConfig,
        IBlogCache cache,
        IMediator mediator)
    {
        _blogConfig = blogConfig;
        _cache = cache;
        _mediator = mediator;
    }

    [HttpGet("opml")]
    public async Task<IActionResult> Opml()
    {
        var cats = await _mediator.Send(new GetCategoriesQuery());
        var catInfos = cats.Select(c => new KeyValuePair<string, string>(c.DisplayName, c.RouteName));
        var rootUrl = Helper.ResolveRootUrl(HttpContext);

        var oi = new OpmlDoc
        {
            SiteTitle = $"{_blogConfig.GeneralSettings.SiteTitle} - OPML",
            ContentInfo = catInfos,
            HtmlUrl = $"{rootUrl}/post",
            XmlUrl = $"{rootUrl}/rss",
            XmlUrlTemplate = $"{rootUrl}/rss/[catTitle]",
            HtmlUrlTemplate = $"{rootUrl}/category/[catTitle]"
        };

        var xml = await _mediator.Send(new GetOpmlQuery(oi));
        return Content(xml, "text/xml");
    }

    [HttpGet("rss/{routeName?}")]
    public async Task<IActionResult> Rss([MaxLength(64)] string routeName = null)
    {
        bool hasRoute = !string.IsNullOrWhiteSpace(routeName);
        var route = hasRoute ? routeName.ToLower().Trim() : null;

        return await _cache.GetOrCreateAsync(
            hasRoute ? CacheDivision.RssCategory : CacheDivision.General, route ?? "rss", async entry =>
            {
                entry.SlidingExpiration = TimeSpan.FromHours(1);

                var xml = await _mediator.Send(new GetRssStringQuery(routeName));
                if (string.IsNullOrWhiteSpace(xml))
                {
                    return (IActionResult)NotFound();
                }

                return Content(xml, "text/xml");
            });
    }

    [HttpGet("atom")]
    public async Task<IActionResult> Atom()
    {
        return await _cache.GetOrCreateAsync(CacheDivision.General, "atom", async entry =>
        {
            entry.SlidingExpiration = TimeSpan.FromHours(1);

            var xml = await _mediator.Send(new GetAtomStringQuery());
            return Content(xml, "text/xml");
        });
    }
}

src/Moonglade.Web/Controllers/TagsController.cs
using MoongladePure.Caching.Filters;
using MoongladePure.Core.TagFeature;
using System.ComponentModel.DataAnnotations;

namespace MoongladePure.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class TagsController : ControllerBase
{
    private readonly IMediator _mediator;

    public TagsController(IMediator mediator) => _mediator = mediator;

    [HttpGet("names")]
    [ProducesResponseType(typeof(IReadOnlyList<string>), StatusCodes.Status200OK)]
    public async Task<IActionResult> Names()
    {
        var tagNames = await _mediator.Send(new GetTagNamesQuery());
        return Ok(tagNames);
    }

    [HttpPost]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> Create([Required][FromBody] string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return BadRequest();
        if (!Tag.ValidateName(name)) return Conflict();

        await _mediator.Send(new CreateTagCommand(name.Trim()));
        return Ok();
    }

    [HttpPut("{id:int}")]
    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { BlogCacheType.PagingCount })]
    [ApiConventionMethod(typeof(DefaultApiConventions), nameof(DefaultApiConventions.Put))]
    public async Task<IActionResult> Update([Range(1, int.MaxValue)] int id, [Required][FromBody] string name)
    {
        var oc = await _mediator.Send(new UpdateTagCommand(id, name));
        if (oc == OperationCode.ObjectNotFound) return NotFound();

        return NoContent();
    }

    [HttpDelete("{id:int}")]
    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { BlogCacheType.PagingCount })]
    [ApiConventionMethod(typeof(DefaultApiConventions), nameof(DefaultApiConventions.Delete))]
    public async Task<IActionResult> Delete([Range(0, int.MaxValue)] int id)
    {
        var oc = await _mediator.Send(new DeleteTagCommand(id));
        if (oc == OperationCode.ObjectNotFound) return NotFound();

        return NoContent();
    }
}

src/Moonglade.Web/Pages/Admin/Post.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using MoongladePure.Core.PostFeature;
using MoongladePure.Data.Spec;
using System.ComponentModel.DataAnnotations;
using X.PagedList;

namespace MoongladePure.Web.Pages.Admin;

public class PostModel : PageModel
{
    private readonly IMediator _mediator;
    private const int PageSize = 7;

    [BindProperty]
    [MaxLength(32)]
    public string SearchTerm { get; set; }

    public StaticPagedList<PostSegment> PostSegments { get; set; }

    public PostModel(IMediator mediator) => _mediator = mediator;

    public async Task OnPost()
    {
        await GetPosts(1);
    }

    public async Task OnGet(int pageIndex = 1, string searchTerm = null)
    {
        if (!string.IsNullOrWhiteSpace(searchTerm)) SearchTerm = searchTerm;

        await GetPosts(pageIndex);
    }

    private async Task GetPosts(int pageIndex)
    {
        var (posts, totalRows) = await _mediator.Send(new ListPostSegmentQuery(PostStatus.Published, (pageIndex - 1) * PageSize, PageSize, SearchTerm));
        PostSegments = new(posts, pageIndex, PageSize, totalRows);
    }
}

src/Moonglade.Web/Pages/ArchiveList.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using MoongladePure.Core.PostFeature;

namespace MoongladePure.Web.Pages;

public class ArchiveListModel : PageModel
{
    private readonly IMediator _mediator;

    public IReadOnlyList<PostDigest> Posts { get; set; }

    public string ArchiveInfo { get; set; }

    public ArchiveListModel(IMediator mediator) => _mediator = mediator;

    public async Task<IActionResult> OnGetAsync(int year, int? month)
    {
        if (year < DateTime.MinValue.Year || year > DateTime.UtcNow.Year) return BadRequest();
        if (month is > 12 or < 0) return BadRequest();

        IReadOnlyList<PostDigest> model;

        if (month is not null)
        {
            // {year}/{month}
            ArchiveInfo = $"{year}.{month}";
            model = await _mediator.Send(new ListArchiveQuery(year, month));
        }
        else
        {
            // {year}
            ArchiveInfo = $"{year}";
            model = await _mediator.Send(new ListArchiveQuery(year));
        }

        Posts = model;
        return Page();
    }
}

src/Moonglade.Web/Pages/BlogPage.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using MoongladePure.Core.PageFeature;

namespace MoongladePure.Web.Pages;

public class BlogPageModel : PageModel
{
    private readonly IMediator _mediator;

    private readonly IBlogCache _cache;
    private readonly IConfiguration _configuration;
    public BlogPage BlogPage { get; set; }

    public BlogPageModel(
        IMediator mediator, IBlogCache cache, IConfiguration configuration)
    {
        _cache = cache;
        _configuration = configuration;
        _mediator = mediator;
    }

    public async Task<IActionResult> OnGetAsync(string slug)
    {
        if (string.IsNullOrWhiteSpace(slug)) return BadRequest();

        var page = await _cache.GetOrCreateAsync(CacheDivision.Page, slug.ToLower(), async entry =>
        {
            entry.SlidingExpiration = TimeSpan.FromMinutes(int.Parse(_configuration["CacheSlidingExpirationMinutes:Page"] ?? "0"));

            var p = await _mediator.Send(new GetPageBySlugQuery(slug));
            return p;
        });

        if (page is null || !page.IsPublished) return NotFound();

        BlogPage = page;
        return Page();
    }
}

src/Moonglade.Web/Pages/CategoryList.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using MoongladePure.Core.CategoryFeature;
using MoongladePure.Core.PostFeature;
using X.PagedList;

namespace MoongladePure.Web.Pages;

public class CategoryListModel : PageModel
{
    private readonly IMediator _mediator;
    private readonly IBlogConfig _blogConfig;
    private readonly IBlogCache _cache;

    [BindProperty(SupportsGet = true)]
    public int P { get; set; }
    public StaticPagedList<PostDigest> Posts { get; set; }
    public Category Cat { get; set; }

    public CategoryListModel(
        IBlogConfig blogConfig,
        IMediator mediator,
        IBlogCache cache)
    {
        _blogConfig = blogConfig;
        _mediator = mediator;
        _cache = cache;

        P = 1;
    }

    public async Task<IActionResult> OnGetAsync(string routeName)
    {
        if (string.IsNullOrWhiteSpace(routeName)) return NotFound();

        var pageSize = _blogConfig.ContentSettings.PostListPageSize;
        Cat = await _mediator.Send(new GetCategoryByRouteQuery(routeName));

        if (Cat is null) return NotFound();

        var postCount = await _cache.GetOrCreateAsync(CacheDivision.PostCountCategory, Cat.Id.ToString(),
            _ => _mediator.Send(new CountPostQuery(CountType.Category, Cat.Id)));

        var postList = await _mediator.Send(new ListPostsQuery(pageSize, P, Cat.Id));

        Posts = new(postList, P, pageSize, postCount);
        return Page();
    }
}

src/Moonglade.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MoongladePure.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
public class ErrorModel : PageModel
{
    private readonly ILogger<ErrorModel> _logger;

    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        var requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        var exceptionFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
        if (exceptionFeature is not null)
        {
            // Get the exception that occurred
            var exceptionThatOccurred = exceptionFeature.Error;
            _logger.LogError("Error: {RouteWhereExceptionOccurred}, client IP: {ClientIp}, request id: {RequestId}", 
                exceptionThatOccurred.Message, 
                Helper.GetClientIP(HttpContext), 
                requestId);
        }

        RequestId = requestId;
    }
}

src/Moonglade.Web/Pages/Featured.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using MoongladePure.Core.PostFeature;
using X.PagedList;

namespace MoongladePure.Web.Pages;

public class FeaturedModel : PageModel
{
    private readonly IBlogConfig _blogConfig;
    private readonly IMediator _mediator;
    private readonly IBlogCache _cache;
    public StaticPagedList<PostDigest> Posts { get; set; }

    public FeaturedModel(
        IBlogConfig blogConfig, IBlogCache cache, IMediator mediator)
    {
        _blogConfig = blogConfig;
        _cache = cache;
        _mediator = mediator;
    }

    public async Task OnGet(int p = 1)
    {
        var pagesize = _blogConfig.ContentSettings.PostListPageSize;
        var posts = await _mediator.Send(new ListFeaturedQuery(pagesize, p));
        var count = await _cache.GetOrCreateAsync(CacheDivision.PostCountFeatured, "featured", _ => _mediator.Send(new CountPostQuery(CountType.Featured)));

        var list = new StaticPagedList<PostDigest>(posts, p, pagesize, count);
        Posts = list;
    }
}

src/Moonglade.Web/ViewComponents/CommentListViewComponent.cs
namespace MoongladePure.Web.ViewComponents;

public class CommentListViewComponent : ViewComponent
{
    private readonly ILogger<CommentListViewComponent> _logger;
    private readonly IMediator _mediator;

    public CommentListViewComponent(
        ILogger<CommentListViewComponent> logger, IMediator mediator)
    {
        _logger = logger;
        _mediator = mediator;
    }

    public async Task<IViewComponentResult> InvokeAsync(Guid postId)
    {
        try
        {
            if (postId == Guid.Empty)
            {
                _logger.LogError("postId: {PostId} is not a valid GUID", postId);
                throw new ArgumentOutOfRangeException(nameof(postId));
            }

            var comments = await _mediator.Send(new GetApprovedCommentsQuery(postId));
            return View(comments);
        }
        catch (Exception e)
        {
            _logger.LogError(e, "Error reading comments for post id: {PostId}", postId);
            return Content(e.Message);
        }
    }
}

src/Moonglade.Web/Pages/Archive.cshtml
@page "/archive"
@using System.Globalization
@using MoongladePure.Core.PostFeature
@inject IMediator Mediator
@{
    ViewBag.TitlePrefix = "Archive ";
    var archives = await Mediator.Send(new GetArchiveQuery());
    int[] yearList = null;
    if (null != Model && archives.Any())
    {
        yearList = (from item in archives
                    orderby item.Year descending
                    select item.Year).Distinct().ToArray();
    }

    static string GetMonthNameByNumber(int number)
    {
        return number is > 12 or < 1 ? 
            string.Empty : 
            CultureInfo.GetCultureInfo("en-US").DateTimeFormat.GetMonthName(number);
    }
}

@section head{
    <link href="~/css/timeline.css" rel="stylesheet" asp-append-version="true" />
}

<h3>
    @SharedLocalizer["Archive Timeline"]
</h3>
<hr />

@if (null != Model && archives.Any() && null != yearList)
{
    <ul class="timeline" id="monthList">
        @foreach (var item in yearList)
        {
            var queryMonth = archives.Where(obj => obj.Year == item);
            var yearEndChar = item % 10;
            var badgeClass = (yearEndChar % 5) switch
            {
                0 => "primary",
                1 => "success",
                2 => "info",
                3 => "warning",
                4 => "danger",
                _ => string.Empty
            };

            <li class="@(item % 2 == 0 ? "timeline-inverted" : null)">
                <div class="timeline-badge @badgeClass"><i class="bi-calendar2-week"></i></div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h3 class="timeline-title">
                            <a asp-page="./ArchiveList" asp-route-year="@item">@item</a>
                        </h3>
                    </div>
                    <div class="timeline-body">
                        <div class="row g-2">
                            @foreach (var month in queryMonth.OrderByDescending(m => m.Month))
                            {
                                <div class="col-md-6 col-sm-6 col-6">
                                    <span class="badge bg-secondary float-end">@(month.Count)</span>
                                    <a asp-page="./ArchiveList"
                                       asp-route-year="@month.Year"
                                       asp-route-month="@month.Month">
                                        @GetMonthNameByNumber(month.Month)
                                    </a>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </li>
        }
    </ul>
}
else
{
    <div class="alert alert-info">@SharedLocalizer["No Archive"]</div>
}

<partial name="_LightSwitch" />

src/Moonglade.Web/Pages/ArchiveList.cshtml
@page "/archive/{year:int:length(4)}/{month:int:range(1,12)?}"
@model MoongladePure.Web.Pages.ArchiveListModel
@{
    ViewBag.TitlePrefix = $"All Posts in {Model.ArchiveInfo}";
}

<h3>
    @ViewBag.TitlePrefix
</h3>
<hr />
<div>
    @if (!Model.Posts.Any())
    {
        <div class="alert alert-warning">
            @SharedLocalizer["No Posts"]
        </div>
    }
    else
    {
        foreach (var item in Model.Posts.OrderByDescending(s => s.PubDateUtc))
        {
            <partial name="_PostListEntry" model="item" />
            <div class="mb-4 d-none d-md-block"></div>
            <hr class="d-none d-md-block" />
        }
    }
</div>

<partial name="_LightSwitch" />

src/Moonglade.Web/Pages/BlogPage.cshtml
@page "/page/{slug:regex(^(?!-)([a-zA-Z0-9-]){{1,128}}$)}"
@model MoongladePure.Web.Pages.BlogPageModel
@using NUglify
@using MoongladePure.Utils

@{
    ViewBag.TitlePrefix = Model.BlogPage.Title;
    ViewBag.HideSideBar = Model.BlogPage.HideSidebar;
    ViewBag.DisableLightSwitch = true;

    string css = null;
    if (!string.IsNullOrWhiteSpace(Model.BlogPage.CssContent))
    {
        var uglifyResult = Uglify.Css(Model.BlogPage.CssContent);
        if (!uglifyResult.HasErrors)
        {
            css = uglifyResult.Code;
        }
    }

}

@section head{
    <link href="~/css/timeline.css" rel="stylesheet" asp-append-version="true" />

    @if (!string.IsNullOrWhiteSpace(css))
    {
        <style>
            @Html.Raw(css)
        </style>
    }
}

@section metadescription{
    <metadesc description="@Model.BlogPage.MetaDescription" />
}

@if (null != ViewBag.IsDraftPreview)
{
    <div class="container mt-3 mb-4">
        <div class="alert alert-info">
            @SharedLocalizer["This is a preview for draft content."]
        </div>
    </div>
}

<div class="page-content">
    @if (BlogConfig.AdvancedSettings.AllowScriptsInPage)
    {
        @Html.Raw(Model.BlogPage.RawHtmlContent)
    }
    else
    {
        @Html.Raw(Helper.RemoveScriptTagFromHtml(Model.BlogPage.RawHtmlContent))
    }
</div>

<partial name="_PageForestageAdmin" />

src/Moonglade.Web/Pages/CategoryList.cshtml
@page "/category/{routeName:regex(^(?!-)([a-zA-Z0-9-]){{1,64}}$)}"
@model MoongladePure.Web.Pages.CategoryListModel
@{
    ViewBag.TitlePrefix = Model.Cat.DisplayName;
    ViewBag.ActionName = "list";
}

<h3>
    <a class="float-end d-none d-md-block"
       asp-controller="Subscription"
       asp-action="Rss"
       asp-route-routeName="@Model.Cat.RouteName.ToLower()" target="_blank"
       title="Subscribe @(Model.Cat.DisplayName)">
        <i class="bi-rss font-125rem"></i>
    </a>
    <span>@Model.Cat.DisplayName</span>
    <small class="d-none d-md-inline text-muted">@Model.Cat.Note</small>
</h3>
<hr />
@if (Model.Posts.Any())
{
    <partial name="_PostList" model="Model.Posts" />
}
else
{
    <div class="alert alert-info">
        @SharedLocalizer["No Posts"]
    </div>
}

<partial name="_LightSwitch" />

src/Moonglade.Web/Pages/PostPreview.cshtml
@page "/post/preview/{postId:guid}"
@model MoongladePure.Web.Pages.PostPreviewModel
@using MoongladePure.Utils
@using NUglify

@{
    ViewBag.BodyClass = "body-post-slug";
}

@section meta {
    <meta name="robots" content="noindex, nofollow" />
    <meta name="title" content="@Model.Post.Title" />
    <meta name="author" content="@(string.IsNullOrWhiteSpace(Model.Post.Author) ? BlogConfig.GeneralSettings.OwnerName : Model.Post.Author) " />
    <link href="~/css/post-slug.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/highlighter-custom.css" rel="stylesheet" asp-append-version="true" />

    @if (!string.IsNullOrWhiteSpace(Model.Post.InlineCss))
    {
        var uglifiedCss = Uglify.Css(Model.Post.InlineCss);
        if (!uglifiedCss.HasErrors)
        {
            <style>
                @uglifiedCss.Code
            </style>
        }
    }
}

@section scripts {
    <script src="~/js/3rd/highlight.min.js" asp-append-version="true"></script>
    <script type="module">
        import * as viewpost from '/js/app/viewpost.module.js'

        window.fitImageToDevicePixelRatio = @BlogConfig.ImageSettings.FitImageToDevicePixelRatio.ToString().ToLower();
        viewpost.resizeImages();
        viewpost.renderCodeHighlighter();

        if (window.innerWidth >= 768) {
            viewpost.applyImageZooming();
        }

        @if (BlogConfig.AdvancedSettings.WarnExternalLink)
        {
            <text>
                postSlug.warnExtLink();
            </text>
        }
    </script>
}

<div class="alert alert-info">
    @SharedLocalizer["This is a preview for draft content."]
</div>

<article class="article-post-slug box border position-relative mb-4" data-postid="@Model.Post.Id" lang="@Model.Post.ContentLanguageCode">
    @if (Model.Post.Featured)
    {
        <partial name="_FeaturedTag" />
    }

    <header class="post-header @(BlogConfig.ContentSettings.PostTitleAlignment == PostTitleAlignment.Center ? "text-center" : null)">
        <h1 class="post-title">
            @Model.Post.Title
        </h1>

        <hr class="d-none d-md-block" />
    </header>

    @if (!string.IsNullOrWhiteSpace(Model.Post.HeroImageUrl))
    {
        <div class="post-hero-image-container text-center mb-3">
            <img src="@Helper.SterilizeLink(Model.Post.HeroImageUrl)" class="post-hero-image img-fluid rounded-3 shadow-sm" />
        </div>
    }

    <section class="post-content clearfix">
        <partial name="_PostContentRender" model="Model.Post.RawPostContent" />
    </section>
    @if (BlogConfig.ContentSettings.ShowPostFooter)
    {
        <section class="post-footer clearfix">
            @Html.Raw(BlogConfig.ContentSettings.PostFooterHtmlPitch)
        </section>
    }

    <partial name="_PostActions" model="Model.Post" />
    
    @if (!string.IsNullOrWhiteSpace(Model.Post.OriginLink))
    {
        <a href="@Helper.SterilizeLink(Model.Post.OriginLink)" target="_blank">
            <i class="bi-link"></i>
            @SharedLocalizer["Read origin article"]
        </a>
    }
</article>

<partial name="_LightSwitch" />

<div class="modal fade" id="imgzoomModal" tabindex="-1" role="dialog" aria-labelledby="imgzoomModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-imgzoom" role="document" style="max-width: 100%">
        <div class="modal-content">
            <img id="imgzoom" alt="imgzoom" class="img-fluid" />
        </div>
    </div>
</div>

@if (BlogConfig.AdvancedSettings.WarnExternalLink)
{
    <partial name="_ExternalLink" />
}

<partial name="_PostForestageAdmin" />

src/Moonglade.Web/Pages/_FeaturedTag.cshtml
<a asp-page="/Featured">
    <img src="~/images/featured-post.svg" class="featured-post-banner position-absolute d-none d-md-block" title="@SharedLocalizer["Featured"]" alt="@SharedLocalizer["Featured"]" />
</a>