src/Moonglade.Web/Controllers/CategoryController.cs
using MoongladePure.Core.CategoryFeature;
using MoongladePure.Web.Attributes;

namespace MoongladePure.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class CategoryController : ControllerBase
{
    private readonly IMediator _mediator;

    public CategoryController(IMediator mediator) => _mediator = mediator;

    [HttpGet("{id:guid}")]
    [ProducesResponseType(typeof(Category), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Get([NotEmpty] Guid id)
    {
        var cat = await _mediator.Send(new GetCategoryByIdQuery(id));
        if (null == cat) return NotFound();

        return Ok(cat);
    }

    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    public async Task<IActionResult> Create(CreateCategoryCommand command)
    {
        await _mediator.Send(command);
        return Created(string.Empty, command);
    }

    [HttpPut("{id:guid}")]
    [ApiConventionMethod(typeof(DefaultApiConventions), nameof(DefaultApiConventions.Put))]
    public async Task<IActionResult> Update([NotEmpty] Guid id, UpdateCategoryCommand command)
    {
        command.Id = id;
        var oc = await _mediator.Send<OperationCode>(command);
        if (oc == OperationCode.ObjectNotFound) return NotFound();

        return NoContent();
    }

    [HttpDelete("{id:guid}")]
    [ApiConventionMethod(typeof(DefaultApiConventions), nameof(DefaultApiConventions.Delete))]
    public async Task<IActionResult> Delete([NotEmpty] Guid id)
    {
        var oc = await _mediator.Send(new DeleteCategoryCommand(id));
        if (oc == OperationCode.ObjectNotFound) return NotFound();

        return NoContent();
    }
}

src/Moonglade.Web/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using MoongladePure.Web.Attributes;
using System.ComponentModel.DataAnnotations;

namespace MoongladePure.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
[CommentProviderGate]
public class CommentController : ControllerBase
{
    private readonly IMediator _mediator;
    private readonly IBlogConfig _blogConfig;

    public CommentController(
        IMediator mediator,
        IBlogConfig blogConfig)
    {
        _mediator = mediator;
        _blogConfig = blogConfig;
    }

    [HttpPost("{postId:guid}")]
    [AllowAnonymous]
    [ServiceFilter(typeof(ValidateCaptcha))]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ModelStateDictionary), StatusCodes.Status409Conflict)]
    public async Task<IActionResult> Create([NotEmpty] Guid postId, CommentRequest request)
    {
        if (!string.IsNullOrWhiteSpace(request.Email) && !Helper.IsValidEmailAddress(request.Email))
        {
            ModelState.AddModelError(nameof(request.Email), "Invalid Email address.");
            return BadRequest(ModelState.CombineErrorMessages());
        }

        if (!_blogConfig.ContentSettings.EnableComments) return Forbid();

        var ip = (bool)HttpContext.Items["DNT"] ? "N/A" : Helper.GetClientIP(HttpContext);
        var item = await _mediator.Send(new CreateCommentCommand(postId, request, ip));

        if (item is null)
        {
            ModelState.AddModelError(nameof(request.Content), "Your comment contains bad bad word.");
            return Conflict(ModelState);
        }

        if (_blogConfig.ContentSettings.RequireCommentReview)
        {
            return Created("moonglade://empty", item);
        }

        return Ok();
    }

    [HttpPut("{commentId:guid}/approval/toggle")]
    [ProducesResponseType(typeof(Guid), StatusCodes.Status200OK)]
    public async Task<IActionResult> Approval([NotEmpty] Guid commentId)
    {
        await _mediator.Send(new ToggleApprovalCommand(new[] { commentId }));
        return Ok(commentId);
    }

    [HttpDelete]
    [ProducesResponseType(typeof(Guid[]), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(string), StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> Delete([FromBody][MinLength(1)] Guid[] commentIds)
    {
        await _mediator.Send(new DeleteCommentsCommand(commentIds));
        return Ok(commentIds);
    }

    [HttpPost("{commentId:guid}/reply")]
    [ProducesResponseType(typeof(CommentReply), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    public async Task<IActionResult> Reply(
        [NotEmpty] Guid commentId,
        [Required][FromBody] string replyContent,
        [FromServices] LinkGenerator linkGenerator)
    {
        if (!_blogConfig.ContentSettings.EnableComments) return Forbid();

        var reply = await _mediator.Send(new ReplyCommentCommand(commentId, replyContent));

        return Ok(reply);
    }
}

src/Moonglade.Web/Controllers/DataPortingController.cs
using MoongladePure.Data.Exporting;

namespace MoongladePure.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class DataPortingController : ControllerBase
{
    private readonly IMediator _mediator;

    public DataPortingController(IMediator mediator) => _mediator = mediator;

    [HttpGet("export/{type}")]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> ExportDownload(ExportType type, CancellationToken ct)
    {
        var exportResult = type switch
        {
            ExportType.Tags => await _mediator.Send(new ExportTagsDataCommand(), ct),
            ExportType.Categories => await _mediator.Send(new ExportCategoryDataCommand(), ct),
            ExportType.FriendLinks => await _mediator.Send(new ExportLinkDataCommand(), ct),
            ExportType.Pages => await _mediator.Send(new ExportPageDataCommand(), ct),
            ExportType.Posts => await _mediator.Send(new ExportPostDataCommand(), ct),
            _ => throw new ArgumentOutOfRangeException(nameof(type), type, null)
        };

        switch (exportResult.ExportFormat)
        {
            case ExportFormat.SingleJsonFile:
                return new FileContentResult(exportResult.Content, exportResult.ContentType)
                {
                    FileDownloadName = $"moonglade-{type.ToString().ToLowerInvariant()}-{DateTime.UtcNow:yyyy-MM-dd-HH-mm-ss}.json"
                };

            case ExportFormat.SingleCSVFile:
                Response.Headers.Add("Content-Disposition", $"attachment;filename={Path.GetFileName(exportResult.FilePath)}");
                return PhysicalFile(exportResult.FilePath!, exportResult.ContentType, Path.GetFileName(exportResult.FilePath));

            case ExportFormat.ZippedJsonFiles:
                return PhysicalFile(exportResult.FilePath, exportResult.ContentType, Path.GetFileName(exportResult.FilePath));

            default:
                return BadRequest(ModelState.CombineErrorMessages());
        }
    }
}

src/Moonglade.Web/Controllers/FriendLinkController.cs
using MoongladePure.FriendLink;
using MoongladePure.Web.Attributes;

namespace MoongladePure.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class FriendLinkController : ControllerBase
{
    private readonly IMediator _mediator;

    public FriendLinkController(IMediator mediator) => _mediator = mediator;

    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    public async Task<IActionResult> Create(AddLinkCommand command)
    {
        await _mediator.Send(command);
        return Created(new Uri(command.LinkUrl), command);
    }

    [HttpGet("{id:guid}")]
    [ProducesResponseType(typeof(Link), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Get([NotEmpty] Guid id)
    {
        var link = await _mediator.Send(new GetLinkQuery(id));
        if (null == link) return NotFound();

        return Ok(link);
    }

    [HttpPut("{id:guid}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Update([NotEmpty] Guid id, UpdateLinkCommand command)
    {
        command.Id = id;
        await _mediator.Send(command);
        return NoContent();
    }

    [HttpDelete("{id:guid}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Delete([NotEmpty] Guid id)
    {
        await _mediator.Send(new DeleteLinkCommand(id));
        return NoContent();
    }
}

src/Moonglade.Web/Controllers/LocalAccountController.cs
using MoongladePure.Web.Attributes;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace MoongladePure.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class LocalAccountController : ControllerBase
{
    private readonly IMediator _mediator;

    public LocalAccountController(IMediator mediator) => _mediator = mediator;

    [HttpPost]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> Create(CreateAccountCommand command)
    {
        if (await _mediator.Send(new AccountExistsQuery(command.Username)))
        {
            ModelState.AddModelError("username", $"User '{command.Username}' already exist.");
            return Conflict(ModelState);
        }

        await _mediator.Send(command);
        return Ok();
    }

    [HttpDelete("{id:guid}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> Delete([NotEmpty] Guid id)
    {
        var uidClaim = User.Claims.FirstOrDefault(c => c.Type == "uid");
        if (null == uidClaim || string.IsNullOrWhiteSpace(uidClaim.Value))
        {
            return StatusCode(StatusCodes.Status500InternalServerError, "Can not get current uid.");
        }

        if (id.ToString() == uidClaim.Value)
        {
            return Conflict("Can not delete current user.");
        }

        var count = await _mediator.Send(new CountAccountsQuery());
        if (count == 1)
        {
            return Conflict("Can not delete last account.");
        }

        await _mediator.Send(new DeleteAccountCommand(id));
        return NoContent();
    }

    [HttpPut("{id:guid}/password")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> ResetPassword([NotEmpty] Guid id, [FromBody][Required] string newPassword)
    {
        if (!Regex.IsMatch(newPassword, @"^(?=.*[A-Za-z])(?=.*\d)[!@#$%^&*A-Za-z\d]{8,}$"))
        {
            return Conflict("Password must be minimum eight characters, at least one letter and one number");
        }

        await _mediator.Send(new ChangePasswordCommand(id, newPassword));
        return NoContent();
    }
}

src/Moonglade.Web/Controllers/MenuController.cs
using MoongladePure.Caching.Filters;
using MoongladePure.Menus;
using MoongladePure.Web.Attributes;

namespace MoongladePure.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class MenuController : ControllerBase
{
    private readonly IMediator _mediator;

    public MenuController(IMediator mediator) => _mediator = mediator;

    [HttpPost]
    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { CacheDivision.General, "menu" })]
    [ProducesResponseType(typeof(Guid), StatusCodes.Status200OK)]
    public async Task<IActionResult> Create(EditMenuRequest request)
    {
        var response = await _mediator.Send(new CreateMenuCommand(request));
        return Ok(response);
    }

    [HttpDelete("{id:guid}")]
    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { CacheDivision.General, "menu" })]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Delete([NotEmpty] Guid id)
    {
        await _mediator.Send(new DeleteMenuCommand(id));
        return NoContent();
    }

    [HttpGet("{id:guid}")]
    [ProducesResponseType(typeof(EditMenuRequest), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Edit([NotEmpty] Guid id)
    {
        var menu = await _mediator.Send(new GetMenuQuery(id));
        if (null == menu) return NotFound();

        var model = new EditMenuRequest
        {
            Id = menu.Id,
            DisplayOrder = menu.DisplayOrder,
            Icon = menu.Icon,
            Title = menu.Title,
            Url = menu.Url,
            IsOpenInNewTab = menu.IsOpenInNewTab,
            SubMenus = menu.SubMenus.Select(p => new EditSubMenuRequest
            {
                Id = p.Id,
                Title = p.Title,
                Url = p.Url,
                IsOpenInNewTab = p.IsOpenInNewTab
            }).ToArray()
        };

        return Ok(model);
    }

    [HttpPut("edit")]
    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { CacheDivision.General, "menu" })]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Edit(EditMenuRequest request)
    {
        await _mediator.Send(new UpdateMenuCommand(request));
        return NoContent();
    }
}

src/Moonglade.Web/Controllers/PostController.cs
using MoongladePure.Caching.Filters;
using MoongladePure.Core.PostFeature;
using MoongladePure.Web.Attributes;
using NUglify;
using System.ComponentModel.DataAnnotations;

namespace MoongladePure.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class PostController : ControllerBase
{
    private readonly IMediator _mediator;

    private readonly ILogger<PostController> _logger;

    public PostController(
        IMediator mediator,
        ILogger<PostController> logger)
    {
        _mediator = mediator;
        _logger = logger;
    }

    [HttpPost("createoredit")]
    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[]
    {
        BlogCacheType.SiteMap |
        BlogCacheType.Subscription |
        BlogCacheType.PagingCount
    })]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> CreateOrEdit(PostEditModel model, [FromServices] LinkGenerator linkGenerator)
    {
        try
        {
            if (!ModelState.IsValid) return Conflict(ModelState.CombineErrorMessages());

            if (!string.IsNullOrWhiteSpace(model.InlineCss))
            {
                var uglifyTest = Uglify.Css(model.InlineCss);
                if (uglifyTest.HasErrors)
                {
                    foreach (var err in uglifyTest.Errors)
                    {
                        ModelState.AddModelError(model.InlineCss, err?.ToString() ?? string.Empty);
                    }
                    return BadRequest(ModelState.CombineErrorMessages());
                }

                model.InlineCss = uglifyTest.Code;
            }

            if (model.ChangePublishDate &&
                model.PublishDate.HasValue &&
                model.PublishDate.GetValueOrDefault().Year >= 1975)
            {
                model.PublishDate =model.PublishDate.Value;
            }

            var postEntity = model.PostId == Guid.Empty ?
                await _mediator.Send(new CreatePostCommand(model)) :
                await _mediator.Send(new UpdatePostCommand(model.PostId, model));

            return Ok(new { PostId = postEntity.Id });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error Creating New Post");
            return Conflict(ex.Message);
        }
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[]
    {
        BlogCacheType.SiteMap |
        BlogCacheType.Subscription |
        BlogCacheType.PagingCount
    })]
    [HttpPost("{postId:guid}/restore")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Restore([NotEmpty] Guid postId)
    {
        await _mediator.Send(new RestorePostCommand(postId));
        return NoContent();
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[]
    {
        BlogCacheType.SiteMap |
        BlogCacheType.Subscription |
        BlogCacheType.PagingCount
    })]
    [HttpDelete("{postId:guid}/recycle")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Delete([NotEmpty] Guid postId)
    {
        await _mediator.Send(new DeletePostCommand(postId, true));
        return NoContent();
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { BlogCacheType.Subscription | BlogCacheType.SiteMap })]
    [HttpDelete("{postId:guid}/destroy")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> DeleteFromRecycleBin([NotEmpty] Guid postId)
    {
        await _mediator.Send(new DeletePostCommand(postId));
        return NoContent();
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = new object[] { BlogCacheType.Subscription | BlogCacheType.SiteMap })]
    [HttpDelete("recyclebin")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> EmptyRecycleBin()
    {
        await _mediator.Send(new PurgeRecycledCommand());
        return NoContent();
    }

    [HttpPost("keep-alive")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public IActionResult KeepAlive([MaxLength(16)] string nonce)
    {
        return Ok(new
        {
            ServerTime = DateTime.UtcNow,
            Nonce = nonce
        });
    }
}

src/Moonglade.Web/Pages/Admin/BlogPage.cshtml
@page "/admin/page"
@using MoongladePure.Core.PageFeature
@using System.Globalization
@inject IMediator Mediator
@{
    ViewBag.Title = "Manage Pages";
    var pageSegments = await Mediator.Send(new ListPageSegmentQuery());
}

@section scripts{
<script>
    function deletePage(pageid) {
        callApi(`/api/page/${pageid}`,
            'DELETE',
            {},
            (resp) => {
                document.querySelector(`#card-${pageid}`).remove();
                blogToast.success('Page deleted');
            });
    }

    function deleteConfirm(pageid) {
        var cfm = confirm("Delete Confirmation?");
        if (cfm) deletePage(pageid);
    }
</script>
}

<div class="admin-toolbar ps-4 pe-4 pt-2 pb-2 border-bottom mb-3 shadow-sm">
    <a class="btn btn-outline-accent" asp-page="./EditPage">
        <i class="bi-plus-lg"></i>
        @SharedLocalizer["New"]
    </a>
    
    <a asp-action="ExportDownload" asp-controller="DataPorting" asp-route-type="Pages" class="btn btn-outline-accent" target="_blank">
        <i class="bi-upload"></i>
        @SharedLocalizer["Export"]
    </a>
</div>

@if (pageSegments.Any())
{
    <div class="ps-4 pe-4">
        

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
            @foreach (var item in pageSegments.OrderByDescending(p => p.CreateTimeUtc))
            {
                <div class="col">
                    <div class="card shadow-sm mb-4" id="card-@item.Id">
                        <div class="card-body">
                            <h6 class="card-title">
                                <a asp-page="/BlogPage" asp-route-slug="@item.Slug" target="_blank">@item.Title</a>
                            </h6>
                            <p class="mt-2 h-30px">@item.Slug</p>
                            <small class="text-muted" data-utc-time="@item.CreateTimeUtc.ToString(CultureInfo.InvariantCulture)">
                                
                            </small>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-outline-accent btn-sm btn-edit" asp-page="./EditPage" asp-route-id="@item.Id">
                                <i class="bi-pen"></i>
                            </a>
                            <a class="btn btn-outline-danger btn-sm btn-delete" href="javascript:deleteConfirm('@item.Id');">
                                <i class="bi-trash"></i>
                            </a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}
else
{
    <div class="empty-recycle">
        <div class="text-center">
            <h4>@SharedLocalizer["No Pages"]</h4>
            <p class="text-muted">@SharedLocalizer["no items to show"]</p>
        </div>
    </div>
}

src/Moonglade.Web/Pages/Admin/Category.cshtml
@page "/admin/category"
@model MoongladePure.Web.Pages.Admin.CategoryModel
@{
    ViewBag.Title = "Manage Categories";
}

@section scripts{
<script>
    var editCanvas = new bootstrap.Offcanvas(document.getElementById('editCatCanvas'));
    var catId = window.emptyGuid;

    function initCreateCategory() {
        catId = window.emptyGuid;
        document.querySelector('#edit-form').reset();
        editCanvas.show();
    }

    function editCat(id) {
        callApi(`/api/category/${id}`, 'GET', {},
            async (resp) => {
                var data = await resp.json();
                catId = data.id;
                document.querySelector('#EditCategoryRequest_RouteName').value = data.routeName;
                document.querySelector('#EditCategoryRequest_DisplayName').value = data.displayName;
                document.querySelector('#EditCategoryRequest_Note').value = data.note;
                editCanvas.show();
            });
    }

    function deleteCat(catid) {
        callApi(`/api/category/${catid}`, 'DELETE', {},
            (resp) => {
                document.querySelector(`#card-${catid}`).remove();
                blogToast.success('Category deleted');
            });
    }

    function confirmDelete(catid) {
        var cfm = confirm("Delete?");
        if (cfm) deleteCat(catid);
    }

    function handleSubmit(event) {
        event.preventDefault();

        var apiAddress = '';
        var verb = '';

        if (catId == window.emptyGuid) {
            apiAddress = '/api/category';
            verb = 'POST';
        }
        else {
            apiAddress = `/api/category/${catId}`;
            verb = 'PUT';
        }

        const data = new FormData(event.target);
        const value = Object.fromEntries(data.entries());

        callApi(apiAddress, verb,
            {
                routeName: value["EditCategoryRequest.RouteName"],
                displayName: value["EditCategoryRequest.DisplayName"],
                note: value["EditCategoryRequest.Note"]
            },
            (resp) => {
                document.querySelector('#edit-form').reset();
                editCanvas.hide();
                window.location.reload();
            });
    }

    const form = document.querySelector('#edit-form');
    form.addEventListener('submit', handleSubmit);
</script>
}

<div class="admin-toolbar ps-4 pe-4 pt-2 pb-2 border-bottom mb-3 shadow-sm">
    <a class="btn btn-outline-accent" href="javascript:initCreateCategory();">
        <i class="bi-plus-lg"></i>
        @SharedLocalizer["New"]
    </a>
    
    <a asp-action="ExportDownload" asp-controller="DataPorting" asp-route-type="Categories" class="btn btn-outline-accent" target="_blank">
        <i class="bi-upload"></i>
        @SharedLocalizer["Export"]
    </a>
</div>



<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 ps-4 pe-4">
    @foreach (var cat in Model.Categories.OrderBy(m => m.DisplayName))
    {
        <div class="col">
            <div class="card shadow-sm" id="card-@cat.Id">
                <div class="card-body">
                    <h6 class="card-title">
                        <a asp-page="/CategoryList" asp-route-routeName="@cat.RouteName" target="_blank">
                            @cat.DisplayName
                        </a>
                    </h6>

                    <p class="mt-2 h-30px">
                        @cat.Note
                    </p>

                    <small class="text-muted">@cat.RouteName</small>
                </div>
                <div class="card-footer">
                    <a href="javascript:editCat('@cat.Id');" class="btn btn-sm btn-outline-accent btn-edit"><i class="bi-pen"></i></a>
                    <a href="javascript:confirmDelete('@cat.Id');" class="btn btn-sm btn-outline-danger btn-delete"><i class="bi-trash"></i></a>
                </div>
            </div>
        </div>
    }
</div>

<div class="offcanvas offcanvas-end" tabindex="-1" id="editCatCanvas" aria-labelledby="editCatCanvasLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="editCatCanvasLabel">@SharedLocalizer["Category Information"]</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <form id="edit-form" method="post">
            <div class="mb-3">
                <label class="form-label" asp-for="EditCategoryRequest.DisplayName"></label>
                <input asp-for="EditCategoryRequest.DisplayName" class="form-control" required />
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="EditCategoryRequest.RouteName"></label>
                <input asp-for="EditCategoryRequest.RouteName" class="form-control" required pattern="(?!-)([a-z0-9-]+)" />
                <small class="text-muted">
                    lower case English letters (a-z) and numbers (0-9) with/out hyphen (-) in middle.
                </small>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="EditCategoryRequest.Note"></label>
                <input asp-for="EditCategoryRequest.Note" class="form-control" required />
            </div>
            <div class="mt-3">
                <button type="submit" class="btn btn-success">@SharedLocalizer["Submit"]</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="offcanvas">@SharedLocalizer["Cancel"]</button>
            </div>
        </form>
    </div>
</div>

src/Moonglade.Web/Pages/Admin/_DiagnosisHeader.cshtml
@{
    var currentPage = ViewContext.RouteData.Values["page"]?.ToString();
}

<div class="admin-toolbar ps-4 pe-4 pt-2 pb-2 border-bottom mb-3 shadow-sm d-flex">
    <ul class="nav nav-pills">
        <li role="presentation" class="nav-item nav-item-non-margin">
            <a class="nav-link @(currentPage == "/Admin/About" ? "active" : null)" asp-page="./About">@SharedLocalizer["About"]</a>
        </li>
    </ul>
</div>